### ISSUE TITLE
contentに'<'が含まれるとエラー

### ISSUE THREAD

**Issue by ongaeshi** [kymmt90/hatenablog-writer#1]
文章内に`<`が含まれた記事を投稿しようとするとエラーになるようです。

以下のようなシェルの実行ログをトリプルダッシュで囲んで記事に書こうとすると`<`が含まれてしまうことがあり困っています。

foo.md

```
Failed test

<txt
```

実行例

```
$ bundle exec hw foo.md 
bundler: failed to load command: hw (hw)
NoMethodError: undefined method `[]' for nil:NilClass
  /opt/local/lib/ruby2.3/gems/2.3.0/gems/hatenablog-0.2.1/lib/hatenablog/entry.rb:85:in `parse_document'
  /opt/local/lib/ruby2.3/gems/2.3.0/gems/hatenablog-0.2.1/lib/hatenablog/entry.rb:81:in `initialize'
  /opt/local/lib/ruby2.3/gems/2.3.0/gems/hatenablog-0.2.1/lib/hatenablog/entry.rb:11:in `new'
  /opt/local/lib/ruby2.3/gems/2.3.0/gems/hatenablog-0.2.1/lib/hatenablog/entry.rb:11:in `load_xml'
  /opt/local/lib/ruby2.3/gems/2.3.0/gems/hatenablog-0.2.1/lib/hatenablog/client.rb:94:in `post_entry'
  /Users/ongaeshi/Documents/hatenablog-writer/hb_writer.rb:15:in `post_entry'
  hw:49:in `block (3 levels) in <top (required)>'
  /opt/local/lib/ruby2.3/2.3.0/open-uri.rb:37:in `open'
  /opt/local/lib/ruby2.3/2.3.0/open-uri.rb:37:in `open'
  hw:40:in `block (2 levels) in <top (required)>'
  hw:38:in `each'
  hw:38:in `block in <top (required)>'
  /Users/ongaeshi/Documents/hatenablog-writer/hb_writer.rb:7:in `initialize'
  hw:37:in `new'
  hw:37:in `<top (required)>'
```

`&lt;`などを使えば動くようです。

```
Failed test
<!-- 10328749687177110674 -->
&lt;txt
```

**Comment by ongaeshi** [comment]
最新の hatenablog 0.2.2 を使うことで解決しました。(#2)

**Comment by kymmt90** [comment]
報告ありがとうございました！

hatenablog 0.2.1 では `Client#post_entry` するときヒアドキュメントで XML を作成していて、'`<`' などをエスケープできていなかったため、今回のエラーが起きていたようです。
[hatenablog/client.rb at v0.2.1 · kymmt90/hatenablog](https://github.com/kymmt90/hatenablog/blob/v0.2.1/lib/hatenablog/client.rb#L150)

0.2.2 ではエスケープも実行してくれる `Nokogiri::XML::Builder` で XML を作成しているので、今回パターンでもうまく動きます。
[hatenablog/client.rb at v0.2.2 · kymmt90/hatenablog](https://github.com/kymmt90/hatenablog/blob/v0.2.2/lib/hatenablog/client.rb#L150)

**Comment by ongaeshi** [comment]
ありがとうございます〜、とても便利に使わせてもらっています！ブログの更新がだいぶ楽しくなりました。
